import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { BrowserRouter, Link, NavLink, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { api, download, formToObject } from './api.js';

const AuthContext = createContext(null);
const useAuth = () => useContext(AuthContext);

function AuthProvider({ children }) {
  const [user, setUser] = useState(undefined);
  useEffect(() => { api('/session').then((result) => setUser(result.user)).catch(() => setUser(null)); }, []);
  const value = useMemo(() => ({ user, setUser }), [user]);
  if (user === undefined) return <div className="app-loading">HOBUCO platform...</div>;
  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}

function PublicNav() {
  const [open, setOpen] = useState(false);
  return <div className="behind-nav">
    <header><nav>
      <div className="nav-top"><div className="nav-top-left"><p>Got a Problem? We've Got The Solution! <Link to="/contact-us">Contact Us</Link></p></div><div className="nav-top-right"><p><i className="fas fa-envelope" /> hobucoltd2050@gmail.com</p><p className="nbr"><i className="fas fa-phone" /> +250 788 696 388 | +250 788 213 984</p></div></div>
      <hr />
      <div className="nav-bottom"><div className="nav-bottom-logo"><Link to="/"><h1>HOBUCO</h1></Link></div><div className="nav-links nav-menu"><NavLink to="/" end>Home</NavLink><NavLink to="/about">About Us</NavLink><NavLink to="/services">Services</NavLink><NavLink to="/contact-us">Contact Us</NavLink><NavLink to="/contact-us#contact-form-section">Book a Consultance</NavLink></div><div className="nav-bottom-sociallinks"><div className="social-links-nav"><Link to="/login"><button>Login</button></Link></div><button className="menu-toggle" onClick={() => setOpen(!open)} aria-label="Toggle navigation"><span className="bar" /><span className="bar" /><span className="bar" /></button></div></div>
    </nav></header>
    <div className={`responsive-nav-menu ${open ? 'active' : ''}`}><NavLink to="/" end onClick={() => setOpen(false)}>Home</NavLink><NavLink to="/about" onClick={() => setOpen(false)}>About Us</NavLink><NavLink to="/services" onClick={() => setOpen(false)}>Services</NavLink><NavLink to="/contact-us" onClick={() => setOpen(false)}>Contact Us</NavLink><NavLink to="/contact-us#contact-form-section" onClick={() => setOpen(false)}>Book a Consultance</NavLink></div>
  </div>;
}

function Footer() { return <footer className="footer"><div className="footer-container"><div><h2>HOBUCO</h2><p>Your trusted partner in business excellence.</p></div><div><h3>Quick Links</h3><Link to="/about">About Us</Link><Link to="/services">Services</Link><Link to="/contact-us">Contact Us</Link></div><div><h3>Contact</h3><p>+250 788 696 388</p><p>hobucoltd2050@gmail.com</p><p>Muhanga District, Rwanda</p></div></div><div className="footer-bottom"><p>© {new Date().getFullYear()} HOBUCO Ltd. All rights reserved.</p></div></footer>; }

const serviceData = [
  ['fas fa-chart-line', 'Business Strategy', 'Develop effective business strategies to achieve your goals and maximize growth potential.'],
  ['fas fa-users', 'Research and experimental', 'Research and experimental development in social sciences and humanities.'],
  ['fas fa-money-bill-wave', 'Institutional capacity building', 'Institutional capacity building and internal systems strengthening.'],
  ['fas fa-bullhorn', 'Policy and strategy formulation', 'Policy and strategy formulation, procedure manuals and policies development.']
];

function ConsultationForm() {
  const [message, setMessage] = useState(null);
  async function submit(event) { event.preventDefault(); setMessage(null); try { await api('/book-consultation', { method: 'POST', body: JSON.stringify(formToObject(event.currentTarget)) }); event.currentTarget.reset(); setMessage({ type: 'success', text: 'Thank you. Your consultation request has been submitted.' }); } catch (error) { setMessage({ type: 'error', text: error.message }); } }
  return <form className="contact-form" onSubmit={submit}>{message && <div className={`form-message ${message.type}`}>{message.text}</div>}<div className="form-row"><div className="form-group"><label>First Name</label><input name="firstName" required /></div><div className="form-group"><label>Last Name</label><input name="lastName" required /></div></div><div className="form-row"><div className="form-group"><label>Email</label><input type="email" name="email" required /></div><div className="form-group"><label>Phone</label><input name="phone" /></div></div><div className="form-group"><label>Company / Organization</label><input name="companyOrg" /></div><div className="form-row"><div className="form-group"><label>Subject</label><select name="subject" defaultValue="Consultation"><option>Consultation</option><option>Proposal</option><option>Help</option><option>DevOps</option></select></div><div className="form-group"><label>Service</label><select name="service" defaultValue="Business-Strategy"><option>Business-Strategy</option><option>Research</option><option>Capacity-Building</option><option>Policy-Formulation</option></select></div></div><div className="form-group"><label>Message</label><textarea name="message" rows="5" /></div><button className="btn primary-btn" type="submit">Book Consultation</button></form>;
}

function Home() { return <div className="public-page"><PublicNav /><main>
  <section className="hero-section"><div className="content-left"><h1 className="main-heading">Grow With Expert Advice.</h1><p className="description">HOBUCO Ltd established in the year 2016, is one of the multidisciplinary consulting firms in Rwanda that is goal oriented towards providing sustainable solutions to the challenges in the global consulting arena.</p><div className="cta-buttons"><Link to="/login"><button className="btn btn-primary">Get Started</button></Link><Link to="/about"><button className="btn btn-secondary">Learn More</button></Link></div><div className="services-section"><h3>Our Services:</h3><div className="services-grid">{serviceData.map(([icon, title]) => <div className="service-card" key={title}><div className="service-icon"><i className={icon} /></div><div>{title}</div></div>)}</div></div></div><div className="hero-right"><div className="hero-image-container"><div className="background-circle" /><div className="hero-image"><img alt="HOBUCO expert" src="/images/Dr.Muhayimana-Fulgence_.jpeg" /></div><div className="stat-card stat-main"><div className="stat-icon"><i className="bxr bx-check" /></div><div className="stat-info"><h4>3k+</h4><p>cases solved<br />with satisfaction</p></div></div><div className="stat-card experts-card"><h4>Our Experts</h4><Link to="/about#team-section"><div className="expert-avatars"><div className="expert-avatar">H</div><div className="expert-avatar">F</div><div className="expert-avatar">D</div><div className="expert-avatar">2+</div></div></Link></div></div></div></section>
  <section className="services-content" id="services"><div className="section-header"><h2>Our Services</h2><p>Comprehensive solutions tailored to your needs</p></div><div className="services-container">{serviceData.map(([icon, title, description]) => <div className="service-card" key={title}><div className="service-icon"><i className={icon} /></div><h3>{title}</h3><p>{description}</p><Link to="/about" className="service-link">Learn More <i className="fas fa-arrow-right" /></Link></div>)}<div className="about-features"><div className="about-f-heading"><h3>More Services...</h3></div>{['Baseline, midline and end-line evaluation for both private and public institutions.','Identification, design, appraisal, monitoring and evaluation of development projects.','Education support activities and development of training manuals.','Impact assessment surveys, agroforestry and forestry, soil and water conservation engineering.','Management consultancy activities and trainings.','Outcome harvesting / Mapping.','Results based reporting.','Due diligence preparation.','Partner Capacity Assessment Survey (PCAS) tool.','Grant proposal development.','Support services to forestry.','Other professional, scientific and technical activities.'].map((item) => <div className="feature" key={item}><i className="fas fa-check-circle" /><span>{item}</span></div>)}</div></div></section>
  <section className="why-choose-us-section"><div className="section-header"><h2>Why Choose Us</h2><p>What sets us apart from the competition</p></div><div className="why-choose-container"><div className="why-choose-content">{[['fas fa-handshake','Trusted Expertise','With over 10 years of industry experience, our consultants bring proven expertise to every project.'],['fas fa-lightbulb','Innovative Approach','We combine traditional consulting methods with innovative strategies to deliver cutting-edge solutions.'],['fas fa-chart-pie','Results-Driven','Our focus is on delivering measurable results that directly impact your bottom line.'],['fas fa-users-cog','Tailored Solutions','Each solution is customized to address your specific business challenges and goals.']].map(([icon, title, text]) => <div className="why-choose-item" key={title}><div className="why-choose-icon"><i className={icon} /></div><div className="why-choose-text"><h3>{title}</h3><p>{text}</p></div></div>)}</div><div className="why-choose-image"><img alt="Why Choose Us" src="/images/why-choose-us.jpg" /><div className="experience-badge"><span className="years">10+</span><span className="text">Years of<br />Excellence</span></div></div></div></section>
  <section className="mission-section"><div className="mission-container"><div className="section-header"><h2>Our Mission & Values</h2><p>Guiding principles that drive our success</p></div><div className="mission-grid">{[['fas fa-bullseye','Our Mission','To provide a wide range of high-quality technical assistance and professional services essential for the development and implementation of viable business enterprises and development projects.'],['fas fa-eye','Our Vision','To be a highly ethical and quality service provider to a vibrant private and/or public sector in Rwanda and abroad.'],['fas fa-heart','Our Values','Integrity, Excellence, Innovation, Collaboration, and Client-Centricity form the foundation of everything we do at HOBUCO.']].map(([icon, title, text]) => <div className="mission-card" key={title}><div className="mission-icon"><i className={icon} /></div><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
  <section className="about-section"><div className="about-container"><div className="about-content"><div className="section-header"><h2>About HOBUCO</h2><p>Your trusted partner in business excellence</p></div><p>HOBUCO is a premier consulting firm dedicated to helping businesses achieve their full potential. With our team of experienced consultants, we provide tailored solutions to address your unique challenges.</p><div className="about-features"><div className="feature"><i className="fas fa-check-circle" /><span>10+ Years of Experience</span></div><div className="feature"><i className="fas fa-check-circle" /><span>500+ Satisfied Clients</span></div><div className="feature"><i className="fas fa-check-circle" /><span>Expert Consultants</span></div><div className="feature"><i className="fas fa-check-circle" /><span>Customized Solutions</span></div></div><Link to="/about" className="btn primary-btn">Learn More About Us</Link></div></div></section>
  <section className="contact-section" id="contact-form-section"><div className="section-header"><h2>Book a Consultation</h2><p>Tell us about your challenge and our team will get back to you.</p></div><ConsultationForm /></section>
</main><a className="whatsapp-float" href="https://wa.me/250788696388?text=Hello%20there%2C%20I%20need%20assistance%20with%20your%20services." target="_blank" rel="noreferrer"><i className="fab fa-whatsapp" /></a><Footer /></div>; }

function PublicLayout({ children }) { return <div className="public-page"><PublicNav />{children}<Footer /></div>; }
function About() { return <PublicLayout><main className="simple-page about-page"><h1>About HOBUCO</h1><p>HOBUCO Ltd, established in 2016, is a multidisciplinary consulting firm in Rwanda that provides sustainable, goal-oriented solutions across research, development, capacity building, policy, strategy, and environmental services.</p><div className="about-container"><div className="about-image"><img src="/images/about-img.jpg" alt="About HOBUCO" /></div><div className="about-content"><h2>Our commitment</h2><p>We partner with private and public institutions to deliver high-quality technical assistance in a professional, timely, and cost-effective manner.</p><div className="about-features"><div className="feature"><i className="fas fa-check-circle" /><span>Integrity and accountability</span></div><div className="feature"><i className="fas fa-check-circle" /><span>Experienced consultants</span></div><div className="feature"><i className="fas fa-check-circle" /><span>Practical, measurable outcomes</span></div></div></div></div></main></PublicLayout>; }
function Services() { return <PublicLayout><main className="simple-page services-page"><h1>Our Services</h1><p>HOBUCO delivers multidisciplinary consulting services designed around the needs of each partner.</p><div className="services-container">{serviceData.concat([['fas fa-tree','Environment and development','Environmental assessment, forestry support, land care, and sustainable development solutions.'],['fas fa-file-signature','Proposal and evaluation','Grant proposal development, due diligence, baseline, midline, end-line, and impact evaluations.']]).map(([icon, title, text]) => <div className="service-card" key={title}><div className="service-icon"><i className={icon} /></div><h3>{title}</h3><p>{text}</p><Link to="/contact-us#contact-form-section" className="service-link">Book a Consultance <i className="fas fa-arrow-right" /></Link></div>)}</div></main></PublicLayout>; }
function Contact() { return <PublicLayout><main className="simple-page contact-page"><h1>Contact Us</h1><p>Reach our team for consulting support, partnership opportunities, or a tailored proposal.</p><div className="contact-grid"><div className="contact-info"><h2>Let’s work together</h2><p><i className="fas fa-location-dot" /> Muhanga District, Rwanda</p><p><i className="fas fa-phone" /> +250 788 696 388 / +250 788 213 984</p><p><i className="fas fa-envelope" /> hobucoltd2050@gmail.com</p></div><ConsultationForm /></div></main></PublicLayout>; }

function Auth() {
  const [mode, setMode] = useState('login'); const [message, setMessage] = useState(null); const { setUser } = useAuth(); const navigate = useNavigate();
  async function submit(event) { event.preventDefault(); setMessage(null); const data = formToObject(event.currentTarget); try { const result = await api(mode === 'login' ? '/login' : '/signup', { method: 'POST', body: JSON.stringify(data) }); if (!result.success) return setMessage({ type: 'error', text: result.message }); setMessage({ type: 'success', text: result.message }); if (mode === 'login') { setUser(result.user); navigate('/dashboard'); } } catch (error) { setMessage({ type: 'error', text: error.message }); } }
  return <div className="auth-page"><div className="wrapper"><div className="main-con"><div className="title-text"><div className={`title login ${mode === 'login' ? 'active' : ''}`}>Login Form</div><div className={`title signup ${mode === 'signup' ? 'active' : ''}`}>Signup Form</div></div><div className="form-container"><div className="slide-controls"><button className={`slide login ${mode === 'login' ? 'active' : ''}`} onClick={() => { setMode('login'); setMessage(null); }}>Login</button><button className={`slide signup ${mode === 'signup' ? 'active' : ''}`} onClick={() => { setMode('signup'); setMessage(null); }}>Create Account</button><div className={`slider-tab ${mode}`} /></div>{message && <div className={`form-message ${message.type}`}>{message.text}</div>}<form className={`form-inner ${mode}`} onSubmit={submit}>{mode === 'login' ? <><div className="field"><input name="username" placeholder="Username" autoComplete="username" /></div><div className="field password-field"><input type="password" name="password" placeholder="Password" autoComplete="current-password" /></div><div className="pass-link"><input type="checkbox" name="remember" id="remember" /><span className="remember-text">Remember me.</span></div><div className="field btn"><div className="btn-layer" /><input type="submit" value="Login" /></div><div className="forgot-password"><Link to="/forgot">Forgot Password?</Link></div></> : <><div className="field"><input name="username" placeholder="Username" /></div><div className="field"><input type="email" name="email" placeholder="Email Address" /></div><div className="field"><input type="password" name="password" placeholder="Password" autoComplete="new-password" /></div><div className="field btn"><div className="btn-layer" /><input type="submit" value="Signup" /></div></>}</form></div><div className="back-btn"><Link className="back btn-primary" to="/">Back</Link></div></div></div></div>;
}

function PasswordFlow({ step }) { const [message, setMessage] = useState(null); const navigate = useNavigate(); async function submit(event) { event.preventDefault(); setMessage(null); try { const result = await api(step === 'forgot' ? '/forgot' : step === 'verify' ? '/verify-code' : '/reset-password', { method: 'POST', body: JSON.stringify(formToObject(event.currentTarget)) }); if (!result.success) return setMessage({ type: 'error', text: result.message }); navigate(result.redirectUrl); } catch (error) { setMessage({ type: 'error', text: error.message }); } } const title = step === 'forgot' ? 'Forgot Password' : step === 'verify' ? 'Verify Code' : 'Reset Password'; return <div className="auth-page"><div className="auth-card"><h1>{title}</h1><p>{step === 'forgot' ? 'Enter your email to receive a confirmation code.' : step === 'verify' ? 'Enter the confirmation code sent to your email.' : 'Choose a new password for your account.'}</p>{message && <div className={`form-message ${message.type}`}>{message.text}</div>}<form onSubmit={submit} className="modal-form">{step === 'forgot' && <input type="email" name="email" placeholder="Email Address" required />}{step === 'verify' && <input name="code" placeholder="Confirmation code" required />}{step === 'reset' && <input type="password" name="password" placeholder="New password" required />}<button className="btn btn-primary" type="submit">Continue</button></form><Link to="/login">Back to login</Link></div></div>; }

function Protected({ children, staff = false }) { const { user } = useAuth(); if (!user) return <Navigate to="/login" replace />; if (staff && !['admin', 'manager'].includes(user.role)) return <Navigate to="/dashboard" replace />; return children; }
function DashboardShell({ children, title }) { const { user, setUser } = useAuth(); const navigate = useNavigate(); const [collapsed, setCollapsed] = useState(false); async function logout() { await api('/logout', { method: 'POST' }).catch(() => {}); setUser(null); navigate('/'); } const links = user.role === 'client' ? [['/dashboard','Dashboard','fa-home'],['/client','My Consultations','fa-clipboard-list'],['/help','Help','fa-circle-question']] : [['/dashboard','Dashboard','fa-home'],['/consultations','Consultations','fa-clipboard-list'],['/requests','Requests','fa-inbox'],['/admin/users','Users','fa-users'],['/help','Help','fa-circle-question']]; return <div className={`dashboard-app ${collapsed ? 'sidebar-collapsed' : ''}`}><aside className="sidebar"><div className="sidebar-header"><div className="logo"><span>HOBUCO</span></div><button className="sidebar-toggle" onClick={() => setCollapsed(!collapsed)}><i className="fas fa-bars" /></button></div><ul className="sidebar-menu">{links.map(([to, label, icon]) => <li className="menu-item" key={to}><NavLink className="menu-link" to={to}><i className={`fas ${icon}`} /><span>{label}</span></NavLink></li>)}<li className="menu-item"><button className="menu-link menu-button" onClick={logout}><i className="fas fa-sign-out-alt" /><span>Logout</span></button></li></ul></aside><header className="top-bar"><div className="top-bar-left"><button className="mobile-menu-toggle" onClick={() => setCollapsed(!collapsed)}><i className="fas fa-bars" /></button><h1>{title}</h1></div><div className="top-bar-right"><span>{user.username}</span><span className="role-badge">{user.role}</span></div></header><main className="main-content"><div className="page-content">{children}</div></main></div>; }

function StatCards({ stats, client = false }) { const cards = client ? [['Total Consultations', stats.totalConsultations, 'fa-clipboard-list'], ['Pending', stats.pendingCount, 'fa-clock'], ['Approved', stats.approvedCount, 'fa-check-circle'], ['Dismissed', stats.dismissedCount, 'fa-circle-xmark']] : [['Total Consultations', stats.totalConsultations, 'fa-clipboard-list'], ['Total Users', stats.totalUsers, 'fa-users'], ['Administrators', stats.totalAdmins, 'fa-user-shield'], ['Clients', stats.totalClients, 'fa-user']]; return <div className="stats-grid">{cards.map(([label, value, icon]) => <div className="stat-card-dashboard" key={label}><div className="stat-icon"><i className={`fas ${icon}`} /></div><div><h3>{value ?? 0}</h3><p>{label}</p></div></div>)}</div>; }
function ConsultationTable({ items, onEdit, onDelete, onAction, client = false }) { return <div className="table-container"><table className="data-table"><thead><tr><th>Name</th><th>Email</th><th>Company</th><th>Service</th><th>Date</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.length ? items.map((item) => <tr key={item.id}><td>{item.first_name} {item.last_name}</td><td>{item.email}</td><td>{item.company_org}</td><td>{item.service}</td><td>{item.submitted_at ? new Date(item.submitted_at).toLocaleDateString() : '-'}</td><td><span className={`status-badge status-${item.status}`}>{item.status}</span></td><td className="table-actions">{onEdit && <button className="btn-warning" onClick={() => onEdit(item)}>Edit</button>}{onAction && item.status === 'pending' && <><button className="btn-primary" onClick={() => onAction(item, 'approve')}>Approve</button><button className="btn-danger" onClick={() => onAction(item, 'dismiss')}>Dismiss</button></>}{onDelete && <button className="btn-danger" onClick={() => onDelete(item)}>Delete</button>}</td></tr>) : <tr><td colSpan="7">No consultations found.</td></tr>}</tbody></table></div>; }

function ConsultationModal({ item, onClose, onSaved }) { const [form, setForm] = useState(item ? { ...item, companyOrg: item.company_org } : { first_name: '', last_name: '', email: '', phone: '', companyOrg: '', subject: '', service: '', message: '' }); const [error, setError] = useState(''); function change(event) { setForm({ ...form, [event.target.name]: event.target.value }); } async function submit(event) { event.preventDefault(); setError(''); try { if (item) await api(`/consultations/${item.id}`, { method: 'PUT', body: JSON.stringify(form) }); else await api('/book-consultation', { method: 'POST', body: JSON.stringify(form) }); onSaved(); onClose(); } catch (e) { setError(e.message); } } return <div className="modal-backdrop"><div className="modal-card"><header><h2>{item ? 'Edit Consultation' : 'Add Consultation'}</h2><button onClick={onClose}>×</button></header>{error && <div className="form-message error">{error}</div>}<form className="modal-form" onSubmit={submit}>{[['first_name','First Name'],['last_name','Last Name'],['email','Email'],['phone','Phone'],['companyOrg','Company / Organization'],['subject','Subject'],['service','Service']].map(([name, label]) => <label key={name}>{label}<input name={name} value={form[name] || ''} onChange={change} required={['first_name','last_name','email'].includes(name)} /></label>)}<label>Message<textarea name="message" value={form.message || ''} onChange={change} rows="4" /></label><button className="btn btn-primary" type="submit">Save</button></form></div></div>; }

function Dashboard() { const { user } = useAuth(); const [data, setData] = useState(null); useEffect(() => { api('/dashboard').then(setData).catch(console.error); }, []); if (!data) return <DashboardShell title="Dashboard"><div className="app-loading">Loading dashboard...</div></DashboardShell>; return <DashboardShell title="Dashboard"><div className="dashboard-header"><h2>Welcome back, {user.username}</h2><p>Here is an overview of your HOBUCO workspace.</p></div><StatCards stats={data.stats} client={user.role === 'client'} /><section className="dashboard-card"><div className="card-header"><h3>Recent Consultations</h3><Link to={user.role === 'client' ? '/client' : '/consultations'}>View all</Link></div><ConsultationTable items={data.consultations.slice(0, 5)} client={user.role === 'client'} /></section></DashboardShell>; }

function ConsultationsPage({ client = false }) { const [items, setItems] = useState([]); const [modal, setModal] = useState(null); const [search, setSearch] = useState(''); const { user } = useAuth(); async function load(query = '') { const result = client ? await api('/client') : await api(query ? `/search-consultations?query=${encodeURIComponent(query)}` : '/consultations'); setItems(client ? result.consultations : result.consultations || result); } useEffect(() => { load(); }, []); async function remove(item) { if (!window.confirm(`Delete consultation from ${item.first_name}?`)) return; await api(`/consultations/${item.id}`, { method: 'DELETE' }); load(search); } async function action(item, actionName) { await api(`/requests/action/${item.id}`, { method: 'POST', body: JSON.stringify({ action: actionName }) }); load(search); } return <DashboardShell title={client ? 'My Consultations' : 'Consultations'}><div className="page-toolbar"><div><h2>{client ? 'My Consultations' : 'Consultation Requests'}</h2><p>Manage submitted consultation requests.</p></div><div className="toolbar-actions"><input placeholder="Search consultations" value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && load(search)} />{!client && <><button className="btn btn-primary" onClick={() => setModal({})}>Add New</button><button className="btn btn-secondary" onClick={() => download('/export/consultations')}>Export</button></>}</div></div><ConsultationTable items={items} onEdit={client ? (item) => setModal(item) : (item) => setModal(item)} onDelete={(item) => remove(item)} onAction={!client && user.role !== 'client' ? action : null} />{modal !== null && <ConsultationModal item={Object.keys(modal).length ? modal : null} onClose={() => setModal(null)} onSaved={() => load(search)} />}</DashboardShell>; }

function UsersPage() { const [users, setUsers] = useState([]); const [modal, setModal] = useState(null); const [search, setSearch] = useState(''); async function load(query = '') { const result = await api(query ? `/search-users?query=${encodeURIComponent(query)}` : '/users'); setUsers(result.users || result); } useEffect(() => { load(); }, []); async function remove(user) { if (!window.confirm(`Delete ${user.username}?`)) return; await api(`/users/${user.id}`, { method: 'DELETE' }); load(search); } return <DashboardShell title="Users"><div className="page-toolbar"><div><h2>Users</h2><p>Manage HOBUCO accounts by role.</p></div><div className="toolbar-actions"><input placeholder="Search users" value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && load(search)} /><button className="btn btn-primary" onClick={() => setModal({})}>Add User</button><button className="btn btn-secondary" onClick={() => download('/export/users/all')}>Export</button></div></div><div className="user-role-grid">{['admin','client','manager'].map((role) => <section className="dashboard-card" key={role}><div className="card-header"><h3>{role[0].toUpperCase() + role.slice(1)}s</h3><button className="btn-secondary" onClick={() => download(`/export/users/${role}`)}>Export</button></div><table className="data-table"><thead><tr><th>Username</th><th>Email</th><th>Actions</th></tr></thead><tbody>{users.filter((user) => user.role === role).map((user) => <tr key={user.id}><td>{user.username}</td><td>{user.email}</td><td className="table-actions"><button className="btn-warning" onClick={() => setModal(user)}>Edit</button><button className="btn-danger" onClick={() => remove(user)}>Delete</button></td></tr>)}</tbody></table></section>)}</div>{modal !== null && <UserModal user={Object.keys(modal).length ? modal : null} onClose={() => setModal(null)} onSaved={() => load(search)} />}</DashboardShell>; }
function UserModal({ user, onClose, onSaved }) { const [form, setForm] = useState(user || { username: '', email: '', role: 'client', password: '' }); const [error, setError] = useState(''); function change(e) { setForm({ ...form, [e.target.name]: e.target.value }); } async function submit(e) { e.preventDefault(); try { if (user) await api(`/users/${user.id}`, { method: 'PUT', body: JSON.stringify(form) }); else await api('/signup', { method: 'POST', body: JSON.stringify(form) }); onSaved(); onClose(); } catch (e2) { setError(e2.message); } } return <div className="modal-backdrop"><div className="modal-card"><header><h2>{user ? 'Edit User' : 'Create User'}</h2><button onClick={onClose}>×</button></header>{error && <div className="form-message error">{error}</div>}<form className="modal-form" onSubmit={submit}><label>Username<input name="username" value={form.username || ''} onChange={change} required /></label><label>Email<input type="email" name="email" value={form.email || ''} onChange={change} required /></label><label>Role<select name="role" value={form.role || 'client'} onChange={change}><option value="client">Client</option><option value="manager">Manager</option><option value="admin">Admin</option></select></label><label>Password<input type="password" name="password" value={form.password || ''} onChange={change} placeholder={user ? 'Leave blank to keep current password' : ''} required={!user} /></label><button className="btn btn-primary" type="submit">Save</button></form></div></div>; }

function RequestsPage() { const [items, setItems] = useState([]); const [filter, setFilter] = useState('all'); async function load() { const result = await api('/requests'); setItems(result.consultations); } useEffect(() => { load(); }, []); async function action(item, actionName) { await api(`/requests/action/${item.id}`, { method: 'POST', body: JSON.stringify({ action: actionName }) }); load(); } const filtered = filter === 'all' ? items : items.filter((item) => item.status === filter); return <DashboardShell title="Requests"><div className="page-toolbar"><div><h2>Requests</h2><p>Review and update consultation requests.</p></div><select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="dismissed">Dismissed</option></select></div><StatCards stats={{ totalConsultations: items.length, pendingCount: items.filter((i) => i.status === 'pending').length, approvedCount: items.filter((i) => i.status === 'approved').length, dismissedCount: items.filter((i) => i.status === 'dismissed').length }} client /><ConsultationTable items={filtered} onAction={action} /></DashboardShell>; }
function HelpPage() { return <DashboardShell title="Help"><div className="help-container"><h2>How can we help?</h2><p>Use the sidebar to manage consultations, review requests, export reports, and manage users. For assistance, contact hobucoltd2050@gmail.com or call +250 788 696 388.</p><div className="help-grid"><div className="help-card"><i className="fas fa-circle-question" /><h3>Need support?</h3><p>Our team is available to help you use the HOBUCO platform.</p></div><div className="help-card"><i className="fas fa-envelope" /><h3>Email us</h3><p>hobucoltd2050@gmail.com</p></div></div></div></DashboardShell>; }

function AppRoutes() { return <Routes><Route path="/" element={<Home />} /><Route path="/about" element={<About />} /><Route path="/services" element={<Services />} /><Route path="/contact-us" element={<Contact />} /><Route path="/login" element={<Auth />} /><Route path="/forgot" element={<PasswordFlow step="forgot" />} /><Route path="/verify-code" element={<PasswordFlow step="verify" />} /><Route path="/reset-password" element={<PasswordFlow step="reset" />} /><Route path="/dashboard" element={<Protected><Dashboard /></Protected>} /><Route path="/consultations" element={<Protected staff><ConsultationsPage /></Protected>} /><Route path="/client" element={<Protected><ConsultationsPage client /></Protected>} /><Route path="/admin/users" element={<Protected staff><UsersPage /></Protected>} /><Route path="/requests" element={<Protected staff><RequestsPage /></Protected>} /><Route path="/help" element={<Protected><HelpPage /></Protected>} /><Route path="*" element={<Navigate to="/" replace />} /></Routes>; }

export default function App() { return <BrowserRouter><AuthProvider><AppRoutes /></AuthProvider></BrowserRouter>; }
